# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-clockwork-php-page
  namespace: default # use your namespace here
spec:
  message: Access deined for clockwork files
  tags : ["clockwork","dashboard","exposure"]
  selector:
    matchLabels:
       app: php  # use your own labels here
  file:
    matchPatterns: 
    - pattern: /**/*clockwork/**
    severity: 5 
    action: Block
