apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "datagram-{{.PolicyID}}"
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.AppLabel}}
  kprobes:
  - call: "__cgroup_bpf_run_filter_skb"
    syscall: false
    args:
      - index: 0
        type: sock
      - index: 1
        type: skb
      - index: 2
        type: int
