apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "syscalls-dev-queue-xmit-{{.PolicyID}}"
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.AppLabel}}
  kprobes:
  # long ptrace(enum __ptrace_request request, pid_t pid, void *addr, void *data);
  - call: "dev_queue_xmit"
    syscall: false
    args:
     - index: 0
       type: "skb"
