apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "commit-creds-{{.PolicyID}}"
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.AppLabel}}
  kprobes:
  - call: "commit_creds"
    syscall: false
    args:
    - index: 0
      type:  "cred"
