apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "lsm-{{.PolicyID}}"
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.AppLabel}}
  lsmhooks:
  - hook: "bprm_check_security"
    args:
      - index: 0
        type: "string"
        resolve: "mm.owner.real_parent.real_parent.comm"
    selectors:
      - matchActions:
        - action: Post
