apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "security-override-{{.PolicyID}}"
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.AppLabel}}
  kprobes:
  - call: "security_inode_mkdir"
    syscall: false
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/bash"
    - matchActions:
      - action: Override
        argError: -1
