apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "stack-trces-{{.PolicyID}}"
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.AppLabel}}
  kprobes:
    - call: kfree_skb_reason
      syscall: false
      args:
        - index: 0
          type: skb
        - index: 1
          type: int
          label: "reason"
      selectors:
        - matchActions:
          - action: Post
            kernelStackTrace: true
            userStackTrace: true
