apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "uprobe-binaries-{{.PolicyID}}"
  namespace: {{.Namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.AppLabel}}
  uprobes:
  - path: "/lib64/libc.so.6"
    symbols:
    - "malloc"
    selectors:
    - matchBinaries:
      - operator: "In"
        values:
        - "/usr/bin/bash"
