version: '3.8'

services:
  snfok-postgres:
    image: postgres:latest
    container_name: snfok-postgres
    environment:
      - POSTGRES_PASSWORD=snfok12345
    volumes:
      - snfok-postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  snfok-redis:
    image: redis:latest
    container_name: snfok-redis
    environment:
      - REDIS_PASSWORD=snfok12345
    command: redis-server --requirepass snfok12345
    volumes:
      - snfok-redis-volume:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  snfok-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  snfok-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - snfok-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: snfok-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  snfok-postgres-volume:
    name: snfok-postgres-volume
  snfok-redis-volume:
    name: snfok-redis-volume