version: '3.8'

services:
  snfok-postgres:
    image: postgres:latest
    container_name: snfok-postgres
    environment:
      - POSTGRES_PASSWORD=snfok12345
    volumes:
      - snfok-postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  snfok-redis:
    image: redis:latest
    container_name: snfok-redis
    environment:
      - REDIS_PASSWORD=snfok12345
    command: redis-server --requirepass snfok12345
    volumes:
      - snfok-redis-volume:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  snfok-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  snfok-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - snfok-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: snfok-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.182.2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  snfok-postgres-volume:
    name: snfok-postgres-volume
  snfok-redis-volume:
    name: snfok-redis-volume
  esdata: