export DB_HOST="localhost"
export DB_PORT="5432"
export DB_USER="postgres"
export DB_PASSWORD="snfok12345"
export DB_NAME="snfok"
export DB_SSL_MODE="disable"
export SERVER_PORT="8989"
export LOG_FILE="app.log"
export COOKIE_DOMAIN="localhost"

export POLICIES_TEMPLATES_DIR="/Users/xaadiii/Desktop/SNFOK/agent/policies"
export APPLIED_POLICIES_DIR="/Users/xaadiii/Desktop/SNFOK/agent/tmp"