apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnp-nist-ac-3-3-limit-pod-ingress
  namespace: default  #change with your namespace
spec:
  description: "After applying the policy, This pod only allow connections from inside Namespace"
  endpointSelector:
    matchLabels:
      pod: testpod   #change this label with your label
  ingress:
    - fromEndpoints:
        - {}
