# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-python-hardening-rule-audit-pip
  namespace: default # Change your namespace
spec:
  tags: ["Python", "Hardening Rules", "Audit pip"]
  message: "Pip install execution detected. Python hardening rules violated."
  selector:
    matchLabels:
      app: python #change app: python to match your label
  process:
    severity: 5
    matchPatterns:
    - pattern: /*/*/*/python -m pip install*
    - pattern: /*/*/python -m pip install*
    - pattern: /*/python -m pip install*
    - pattern: /*/*/*/pip install*
    - pattern: /*/*/pip install*
    - pattern: /*/pip install*
    action: Audit
