# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-django-hardening-rule-audit-python-cache
  namespace: default    # Change your namespace
spec:
  tags: ["Python","Django", "Hardening Rules", "Audit cache"]
  message: "Cache folder access detected. Possible violation of basic hardening rules."
  selector:
    matchLabels:
      app: django     #change app: django to match your label
  file:
    severity: 5
    matchDirectories:
    - dir: /root/.cache/pip/     #change folder to or add /home/$USER/.cache/pip/ if you are using a non privileged user
      recursive: true
    action: Audit
