# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-django-hardening-rule-audit-settings-file
  namespace: default    # Change your namespace
spec:
  tags: ["Python","Django", "Hardening Rules", "Audit settings.py"]
  message: "Django settings file access detected. Django hardening rule violated."
  selector:
    matchLabels:
      app: django 	#change app: django to match your label
  file:
    severity: 5
    matchPatterns:
    - pattern: /*/*/*/*/settings.py*
    - pattern: /*/*/*/settings.py*
    - pattern: /*/*/settings.py*
    - pattern: /*/settings.py*
    action: Audit
