apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardening
  namespace: SNFOK
  labels:
    app: hardening
spec:
  selector:
    matchLabels:
      app: hardening
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hardening
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: hardening-api
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
