apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/hardening/
patches:
  - path: ./dev-hardening-patch-deploy.yaml
  - path: ./dev-hardening-patch-service.yaml
images:
  - name: service-image
    newName: localhost/hashx/hardening-api
    newTag: 0.0.1
