# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cis-mongodb-5.1
  namespace: default # Change your namespace
spec:
  tags: ["CIS","MONGODB","5.1"]
  message: "Alert! Audit Log file has been Accessed"
  selector:
    matchLabels:
      app: mongo # Change image labels
  file:
    severity: 3
    matchPaths:
    - path: /data/db/auditLog.json
      ownerOnly: true
    - path: /data/db/auditLog.bson
      ownerOnly: true
    action: Audit
