# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-cis-mongodb-config-file
  namespace: default # Change your namespace
spec:
  tags: ["MONGODB", "CIS"]
  message: "Alert! MongoDB config file has been Accessed."
  selector:
    matchLabels:
      app: mongo # Change image labels
  file:
    severity: 5
    matchPaths:
      - path: /etc/mongod.conf
        ownerOnly: true
    action: Audit
