apiVersion: v1
kind: Namespace
metadata:
  name: SNFOK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardening
  namespace: SNFOK
spec:
  selector:
    matchLabels:
      app: hardening
  replicas: 1
  template:
    metadata:
      labels:
        app: hardening
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: sales-hardening-api
          image: service-image
          ports:
            - name: hardening-api
              containerPort: 3000
            - name: hardening-api-debug
              containerPort: 4000
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
---
kind: Service
apiVersion: v1
metadata:
  name: hardening-api
  namespace: SNFOK
