package response

const (
	QUERY_EXECUTION_FAILED  = 1000
	EMAIL_NOT_VERIFIED      = 1001
	INVALID_EMAIL_PASSWORD  = 1002
	TWO_FACTOR_AUTH_REQ     = 1003
	EXECUTION_ERROR         = 1004
	ACCOUNT_LOCKED          = 1005
	INVALID_REQUEST_PAYLOAD = 1006
	FAILED_DATA_VALIDATION  = 1007
	PASSWORDS_UNMATCHED     = 1008
	CREATION_ERROR          = 1009
)

const (
	LOGIN_SUCCESS       = 1
	CLUSTER_REGISTERED  = 2
	CLUSETR_AVAILABLE   = 3
	NAMESPACES_RESPONSE = 4
	ALL_STATS           = 5
)

const (
	NO_CLUSTER_AVAILABLE          = 2000
	SNFOK_AGENT_IS_NOT_ACCESSABLE = 2001
	CLUSTER_ALREADY_REGISTERED    = 2002
)
