# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nginx-hardening-rule-audit-nginx-reload
  namespace: default # Change your namespace
spec:
  tags: ["Nginx", "Hardening Rules", "Audit nginx reload"]
  message: "Nginx reload detetcted. Possible violation of hardening rules."
  selector:
    matchLabels:
      app: nginx #change app: nginx to match your label
  process:
    severity: 5
    matchPatterns:
    - pattern: /*/*/*/*/nginx -s reload*
    - pattern: /*/*/*/nginx -s reload*
    - pattern: /*/*/nginx -s reload*
    - pattern: /*/nginx -s reload*
    action: Audit
