# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-symbiote-malware-certbotx64-dnscat2
  namespace: default
spec:
  tags: ["MALWARE", "SYMBIOTE","BPF", "NIST", "IR"]
  message: "Alert! certbotx64 and dnscat2 access found! possible symbiote malware!"
  selector:
    matchLabels:
      container: symbiote
  file:
    severity: 1
    matchPaths:
    - path: /etc/host.conf
      readOnly: true
    - path: /etc/ld.so.cache
      readOnly: true
    - path: /etc/resolv.conf
      readOnly: true
    action: Block
  process:
    severity: 1
    matchPaths:
    - path: /lib64/x86_64/libc.so.6
    - path: /lib64/libc.so.6
    - path: /lib64/tls/x86_64/x86_64/libc.so.6
    - path: /lib64/tls/libc.so.6
    - path: /lib64/tls/x86_64/libc.so.6
    - path: /lib64/x86_64/x86_64/libc.so.6
    - path: /lib64/ld-linux-x86-64.so.2
    - path: /lib/x86_64-linux-gnu/libc.so.6
    - path: /dev/urandom
    matchPatterns:
    - pattern: /**/linux-vdso.so.1
    action: Block
