apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-bpfdoor-malware
  namespace: default
spec:
  tags: ["BPF", "BPFDOOR","MALWARE", "NIST", "IR"]
  message: "Alert! /dev/shm/kdmtmpflush file detected possible bpfdoor malware."
  selector:
    matchLabels:
      container: bpfdoor
  process:
    severity: 1
    matchPaths:
    - path: /dev/shm/kdmtmpflush
    - path:  /var/run/haldrund.pid
    matchPatterns:
    - pattern: dbus-daemon
    - pattern: justtryit
    - pattern: justrobot
    - pattern: justforfun
    action: Block
