# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-elastic-exposed-panel
  namespace: default # Change your namespace
spec:
  tags: ["elastic search", "kibana panel", "exposed panel"]
  message: "Alert! Access to kibana panel is detected "
  selector:
    matchLabels:
      container: elastic # Change your labels
  process:
    severity: 4
    matchPatterns:
    - pattern: /**/login
    - pattern: /**/app/kibana
    action: Audit
