# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-nist-au-3-audit-access-to-cmdline-file
spec:
  tags: ["NIST", "NIST-800", "AU-3", "File", "linux"]
  message: "Alert! Access to file cmdline is detected"
  nodeSelector:
    matchLabels:
      node: ubuntu                     #change to your labels
  file:
    severity: 5
    matchPaths:
    - path: /proc/cmdline
    action: Audit
