# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-nist-au-3-audit-bash-config-files
spec:
  tags: ["NIST", "NIST-800", "AU-3", "File", "linux", "NIST_SA", "NIST_SA-20", "NIST_SA-20-Customized Development of Critical Components", "SA"]
  message: "Alert! Access to bash config files detected."
  nodeSelector:
    matchLabels:
      node: ubuntu                     #change to your labels
  file:
    severity: 5
    matchPaths: 
    - path: /etc/profile 
    matchPatterns:
    - pattern: /**/.bash_profile
    - pattern: /**/.bash_login 
    - pattern: /**/.profile
    - pattern: /**/.bashrc
    action: Audit
