# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-nist-cm-3-5-configuration-change-control-automated-security-response 
spec:
  tags: ["NIST","NIST-800-53-r5","CM-3(5)","CONFIGURATION CHANGE CONTROL","AUTOMATED SECURITY RESPONSE"]
  message: "Alert! Baseline configurations change. Explicit mount detected. Possible violation of NIST CM-3(5)"
  nodeSelector:
    matchLabels:
     kubernetes.io/hostname: gke-ubuntu                                                                             # Change your matchLabels
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/mount   
    - path: /bin/mount
    action: Block
