# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-si-4-detect-cron-job-process
  namespace: default # Change your namespace
spec:
  tags: ["NIST", "SI-4", "cron job", "crontab"]
  message: "Alert! Execution of cron job process detected inside the container"
  selector:
    matchLabels:
      app: nginx-test    #change this label with your label
  process:
    severity: 5
    matchPatterns:
    - pattern: /*/crontab
    - pattern: /*/*/crontab
    matchPaths:
    - path: /usr/bin/crontab
    - path: /bin/crontab
    - path: /usr/sbin/crontab
    - path: /sbin/crontab
    action: Audit
