# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-si-4-detect-modify-add-cron-jobs
  namespace: default # Change your namespace
spec:
  tags: ["NIST", "SI-4", "cron job", "crontab"]
  message: "Alert! Detects additions/modifications to cron jobs within the container"
  selector:
    matchLabels:
      app: nginx-test    #change this label with your label
  process:
    severity: 5
    matchPatterns:
    - pattern: /*/*/crontab -e
    - pattern: /*/*/crontab -
    action: Audit
