# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ac-2-4-automated-audit-action
  namespace: default # Change your namespace
spec:
  tags: ["NIST", "system", "account", "NIST-800-53-r5", "AC-2(4)", "Automated audit", "NIST_SA", "NIST_SA-20", "NIST_SA-20-Customized Development of Critical Components", "SA"]
  message: "Alert! use of user account create/edit commands found. Possible violation of NIST controls"
  selector:
    matchLabels:
      app: test # Change your match labels
  file:
    severity: 5
    matchPaths:
    - path: /etc/passwd
    - path: /etc/shadow
    - path: /etc/group
    action: Audit
  process:
    severity: 5
    matchPaths:
    - path: /bin/useradd
    - path: /usr/sbin/useradd
    - path: /bin/adduser
    - path: /usr/sbin/adduser
    - path: /usr/sbin/userdel
    - path: /bin/userdel
    action: Audit
