# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-au-12-block-modification-of-shell-configuration-files
  namespace: default
spec:
  tags: ["NIST","NIST-800-53-r5","AU-12","File Rules","Audit Generation","Deny Modification of Shell Configuration Files", "NIST_SA", "NIST_SA-20", "NIST_SA-20-Customized Development of Critical Components", "SA"]
  message: "Alert! Modification of Shell Configuration Files detected! Possible violation of NIST AU-12 SA-20"
  selector:
    matchLabels:
      app: test-app                                                                                                           #change labels with your label values
  file:
    severity: 5
    matchPaths:
    - path: /root/.bashrc
    - path: /etc/skel/.bashrc
    - path: /etc/skel/.bash_logout
    - path: /root/.inputrc
    - path: /root/.profile
    - path: /etc/skel/.profile
    action: Block
