# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-cm-3-5-configuration-change-control-automated-security-response 
  namespace: default
spec:
  tags: ["NIST","NIST-800-53-r5","CM-3(5)","CONFIGURATION CHANGE CONTROL","AUTOMATED SECURITY RESPONSE"]
  message: "Alert! Baseline configurations change. Explicit mount detected. Possible violation of NIST CM-3(5)"
  selector:
    matchLabels:
      app: test-app                                                                                                           #change labels with your label values
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/mount   
    - path: /bin/mount
    action: Block
