# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/


apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-cm-5-access-restrictions-for-change-bash-history
  namespace: default
spec:
  tags: ["NIST","NIST-800-53-r5","CM-5","ACCESS RESTRICTIONS FOR CHANGE","Bash History"]
  message: "Alert! bash_history file deleteion detected. Possible violation of NIST CM-5"
  selector:
    matchLabels:
      app: ubuntu                                                                                                           #change labels with your label values
  process:
    severity: 5
    matchPaths:
    - path: /root/.bash_history
      fromSource:
      - path: /usr/bin/shred  
      - path: /bin/shred
      - path: /usr/bin/rm
      - path: /bin/rm
      - path: /usr/bin/mv
      - path: /bin/mv
    - path: /home/*/.bash_history
      fromSource:
      - path: /usr/bin/shred  
      - path: /bin/shred
      - path: /usr/bin/rm
      - path: /bin/rm
      - path: /usr/bin/mv
      - path: /bin/mv
    action: Audit
