# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-nist-sc-23-session-authenticity
  namespace: default
spec:
  tags: ["NIST", "SC-23", "LINUX", "SESSION"]
  message: "Alert! SSL/TLs Certificates are accessed!"
  selector:
    matchLabels:
      os: linux
  file:
    severity: 1
    matchDirectories:
    - dir: /etc/ssl/certs/
      readOnly: true
      ownerOnly: true
    - dir: /etc/pki/tls/certs/
      readOnly: true
      ownerOnly: true
    - dir: /etc/ssl/
      readOnly: true
      ownerOnly: true
    - dir: /etc/pki/tls/
      readOnly: true
      ownerOnly: true
    - dir: /etc/pki/ca-trust/extracted/pem/
      readOnly: true
      ownerOnly: true
    action: Audit