# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-au-3-audit-bash-config-files
  namespace: default
spec:
  tags: ["NIST", "NIST-800", "AU-3", "File", "linux"]
  message: "Alert! Access to bash config files detected."
  selector:
    matchLabels:
      app: ubuntu                     #change to your labels
  file:
    severity: 5
    matchPaths: 
    - path: /etc/profile 
    matchPatterns:
    - pattern: /**/.bash_profile
    - pattern: /**/.bash_login 
    - pattern: /**/.profile
    - pattern: /**/.bashrc
    action: Audit
