# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-audit-nist-cm-6-1-linux-config-files
  namespace: default
spec:
  tags: ["NIST", "CM-6-1", "NIST_SA", "NIST_SA-20", "NIST_SA-20-Customized Development of Critical Components", "SA"]
  message: "Alert! config files are accessed! Possible violation of NIST controls."
  selector:
    matchLabels:
      os: linux
  file:
    severity: 1
    matchDirectories:
    - dir: /etc/cups/
    - dir: /etc/xdg/
    - dir: /etc/ssh/
    - dir: /etc/apparmor.d/
    - dir: /etc/udev/
    - dir: /etc/x11/
    - dir: /etc/opt/
    matchPaths:
    - path: /etc/resolv.conf
    - path: /etc/bash.bashrc
    - path: /etc/profile
    - path: /etc/dhcp/dhclient.conf
    - path: /etc/fstab
    - path: /etc/hostname
    - path: /etc/hosts
    - path: /etc/hosts.deny
    - path: /etc/mime.type
    - path: /etc/motd
    - path: /etc/timezone
    - path: /etc/sudoers
    - path: /etc/httpd/conf
    - path: /etc/httpd.conf.d
    - path: /etc/default/grub
    - path: /boot/grub/grub.cfg
    - path: /boot/grub/grub.cfg
    - path: /etc/default/grub
    matchPatterns:
    - pattern: /home/**/.config
    - pattern: /home/**/.xinitrc
    - pattern: /home/**/.vimrc
    - pattern: /home/**/.bashrc
    - pattern: /home/**/.editor
    - pattern: /home/**/.gitconfig
    - pattern: /home/**/.profile
    - pattern: /home/**/.ssh/config
    action: Audit
