# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-ia-3-4-device-attestation-audit
  namespace: default  #change namespace
spec:
  tags: ["NIST", "IA-3(4)", "NIST-SP-800-53"]
  message: "System Device Attestation File Accessed, Possible violation of NIST-IA(3-4)"
  selector:
    matchLabels:
      app: testpod  #change app
  file:
    matchPaths:      
    - path: /etc/securetty
    severity: 5
    action: Audit
