# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ac-10-cred-change-audit
  namespace: default # Change your namespace
spec:
  tags: ["NIST-800", "AC-10", "concurrent-session-control"] 
  message: "Auditing shared and group account credentials change"
  selector:
    matchLabels:
      app: test  #change app: test to match your label
  process:
    severity: 2
    matchPaths:
    - path: /usr/sbin/pwconv
    action: Audit
  file:
    severity: 5
    matchPaths:
    - path: /etc/group
    - path: /etc/group-
    - path: /etc/passwd
    - path: /etc/gshadow
    - path: /etc/gshadow-
    action: Audit
