# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-ac-12-1-sessions-audit
  namespace: default # Change namespace
spec:
  tags: ["NIST-800", "AC-12(1)", "Logging", "session-files", "NIST_SA", "NIST_SA-20", "NIST_SA-20-Customized Development of Critical Components", "SA"]
  message: "Auditing the sensitive,db files. Possible violation of NIST controls"
  selector:
    matchLabels:
      container: ubuntu # Change your match labels
  file:
    severity: 3
    matchPaths:
      - path: /etc/my.cnf
      - path: /etc/profile
      - path: /etc/X11/xorg.conf
      - path: /etc/sudoers
    action: Audit
