# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ac-2-12-account-management-atypical-usage
  namespace: default # Change your namespace
spec:
  tags: ["NIST","NIST-800-53-r5", "AC-2(12)", "Atypical Usage"]
  message: "Notification! Atypical usage of system accounts found. Possible violation of NIST Controls"
  selector:
    matchLabels:
      container: ubuntu-1 # Change your match labels
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/passwd
    - path: /bin/passwd
    - path: /usr/sbin/usermod
    - path: /sbin/usermod
    - path: /usr/sbin/userdel
    - path: /sbin/userdel
    - path: /usr/bin/chage
    - path: /bin/chage
    action: Audit
  file:
    severity: 6
    matchPaths:
    - path: /etc/sudoers
      readOnly: true
    action: Audit
