# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-ca-3-net-udp-audit
  namespace: default
spec:
  tags: ["NIST","NIST-800","CA", "CA-3", "network", "System-Interconnections"]
  message: "Detected Network traffic using udp packets"
  selector:
    matchLabels:
     app: ubuntu                                                                            # Change your matchLabels
  network:
    matchProtocols:
    - protocol: udp
  action:
    Audit
