# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-nist-si-7-1-software-firmware-information-integrity-check
  namespace: default # Change your namespace
spec:
  tags: ["NIST", "NIST-800", "SI-7-1"]
  message: "Alert! Installation of new hardware, software, or firmware detected"
  selector:
    matchLabels:
      app: ubuntu # Change your labels
  process:
    severity: 9
    matchPatterns:
    - pattern: /*/apt-get install *             #new software installation
    - pattern: /*/*/apt-get install * 
    - pattern: /*/apt install * 
    - pattern: /*/*/apt install *
    - pattern: /*/apt install fwupd	         #new firmware installation	
    - pattern: /*/*/apt install fwupd
    - pattern: /*/apt-get install fwupd      
    - pattern: /*/*/apt-get install fwupd
    matchDirectories:
    - dir: /dev/                               #new device file creation 
      recursive: true                       
    action: Audit
