# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-nist-cm-9-config-manage
  namespace: default # Change your namespace
spec:
  tags : ["NIST", "CM-9", "configuration management"] 
  message: "configuration files have been accessed"
  selector:
    matchLabels:
      container: ubuntu    # change to your labels
  file:
    severity: 2 # Higher severity for processes 
    matchPatterns:
    - pattern: /**/*.conf
    - pattern: /*.conf
      ownerOnly: true
    action: Block
