# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-redis-hardening-rule-audit-xautoclaim-command
  namespace: default 																		# Change your namespace
spec:
  tags: ["Redis", "Hardening Rules", "Xautoclaim"]
  message: "XAUTOCLAIM command executed, possible violation of CVE-2022-31144"
  selector:
    matchLabels:
      app: redis 																			#change app: redis to match your label
  process:
    severity: 3
    matchPatterns:
    - pattern: /*/*/*/XAUTOCLAIM
    - pattern: /*/*/XCLAIM
    - pattern: /*/XDEL
    - pattern: /*/*/XAUTOCLAIM
    - pattern: /*/XAUTOCLAIM
    action: Audit
